"""sync models

Revision ID: 4593643d6316
Revises: 831a057075e1
Create Date: 2025-10-19 19:59:14.707931

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4593643d6316"
down_revision: str | Sequence[str] | None = "831a057075e1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema.

    Esta migración se encarga de limpiar tablas/índices legacy si existen.
    En BDs nuevas puede que nunca se hayan creado, por eso usamos IF EXISTS.
    """

    # ---- USERS (legacy) -------------------------------------------------
    # Índices antiguos sobre users
    op.execute(sa.text('DROP INDEX IF EXISTS "ix_users_email";'))
    op.execute(sa.text('DROP INDEX IF EXISTS "ix_users_id";'))

    # Tabla users legacy
    op.execute(sa.text('DROP TABLE IF EXISTS "users" CASCADE;'))

    # ---- PROCESSED_ROWS (legacy) ----------------------------------------
    # Índices antiguos sobre processed_rows
    op.execute(sa.text('DROP INDEX IF EXISTS "ix_processed_rows_id";'))
    op.execute(sa.text('DROP INDEX IF EXISTS "ix_processed_rows_item";'))

    # Tabla processed_rows legacy
    op.execute(sa.text('DROP TABLE IF EXISTS "processed_rows" CASCADE;'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "processed_rows",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("item", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column(
            "amount",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("date_str", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("source_file", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("processed_rows_pkey")),
    )
    op.create_index(op.f("ix_processed_rows_item"), "processed_rows", ["item"], unique=False)
    op.create_index(op.f("ix_processed_rows_id"), "processed_rows", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("email", sa.VARCHAR(length=320), autoincrement=False, nullable=False),
        sa.Column("full_name", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column(
            "hashed_password",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("role", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
        sa.UniqueConstraint(
            "email",
            name=op.f("uq_users_email"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    # ### end Alembic commands ###
