# pyright: reportAttributeAccessIssue=false
"""init

Revision ID: d52be5f91ec4
Revises:
Create Date: 2025-10-05 23:01:48.787738

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d52be5f91ec4"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # Borra solo si existe (evita el fallo en BDs limpias)
    if "saludos" in inspector.get_table_names():
        op.drop_table("saludos")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "saludos",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("mensaje", sa.TEXT(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("saludos_pkey")),
    )
    # ### end Alembic commands ###
